### ISSUE TITLE
Error on sails lift

### ISSUE THREAD

**Issue by devlinpadayachee** [theo4u/sails-hook-swagger-generator#10]
Hi I get and error on sails lift 

our routes { '/csrfToken':
   { target: [Function: csrfToken],
     cors: { origin: '-', credentials: true } },
  '/': { view: 'homepage' } }
error: A hook (`swagger-generator`) failed to load!
error: TypeError: Cannot read property 'http_method' of undefined
    at D:\Google Drive\Ignite Workspace\flow\node_modules\sails-hook-swagger-generator\lib\parsers.js:103:22
    at D:\Google Drive\Ignite Workspace\flow\node_modules\lodash\index.js:3073:15
    at baseForOwn (D:\Google Drive\Ignite Workspace\flow\node_modules\lodash\index.js:2046:14)
    at D:\Google Drive\Ignite Workspace\flow\node_modules\lodash\index.js:3043:18
    at Function.<anonymous> (D:\Google Drive\Ignite Workspace\flow\node_modules\lodash\index.js:3346:13)
    at Object._parseRoutes [as routes] (D:\Google Drive\Ignite Workspace\flow\node_modules\sails-hook-swagger-generator\lib\parsers.js:67:7)
    at Object._generateRoutes [as routes] (D:\Google Drive\Ignite Workspace\flow\node_modules\sails-hook-swagger-generator\lib\generators.js:149:26)
    at module.exports (D:\Google Drive\Ignite Workspace\flow\node_modules\sails-hook-swagger-generator\lib\swaggerDoc.js:15:38)
    at Hook.initialize (D:\Google Drive\Ignite Workspace\flow\node_modules\sails-hook-swagger-generator\index.js:44:13)
    at Hook.wrapper [as initialize] (D:\Google Drive\Ignite Workspace\flow\node_modules\@sailshq\lodash\lib\index.js:3250:19)
    at D:\Google Drive\Ignite Workspace\flow\node_modules\sails\lib\hooks\index.js:88:16
    at D:\Google Drive\Ignite Workspace\flow\node_modules\sails\node_modules\async\lib\async.js:52:16
    at D:\Google Drive\Ignite Workspace\flow\node_modules\sails\node_modules\async\lib\async.js:548:17
    at D:\Google Drive\Ignite Workspace\flow\node_modules\sails\node_modules\async\lib\async.js:542:17
    at _arrayEach (D:\Google Drive\Ignite Workspace\flow\node_modules\sails\node_modules\async\lib\async.js:85:13)
    at Immediate.taskComplete [as _onImmediate] (D:\Google Drive\Ignite Workspace\flow\node_modules\sails\node_modules\async\lib\async.js:541:13)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by theo4u** [comment]
oh check this #7 solved it 👍
