### ISSUE TITLE
swaggerGenerator.js is throwing error

### ISSUE THREAD

**Issue by anasuya1117** [theo4u/sails-hook-swagger-generator#13]
`include-all` attempted to `require(/home/anasuya/Documents/FrescoPlay/date-api/config/swaggergenerator.js)`, but an error occurred:: 
Details:ReferenceError: `sails is not defined`
    at Object.<anonymous> (/home/anasuya/Documents/FrescoPlay/date-api/config/swaggergenerator.js:12:22)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at /home/anasuya/Documents/FrescoPlay/date-api/node_modules/include-all/lib/help-include-all-sync.js:271:33
    at Array.forEach (<anonymous>)
    at _recursivelyIncludeAll (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/include-all/lib/help-include-all-sync.js:174:11)
    at includeAll (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/include-all/lib/help-include-all-sync.js:292:5)
    at helpBuildDictionary (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/include-all/lib/help-build-dictionary.js:43:15)
    at Function.module.exports.aggregate (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/include-all/index.js:101:10)
    at Array.loadOtherConfigFiles (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/sails/lib/hooks/moduleloader/index.js:247:22)
    at /home/anasuya/Documents/FrescoPlay/date-api/node_modules/sails/node_modules/async/lib/async.js:591:38
    at _arrayEach (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/sails/node_modules/async/lib/async.js:85:13)
    at Object.async.auto (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/sails/node_modules/async/lib/async.js:552:9)
    at Hook.loadUserConfig (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/sails/lib/hooks/moduleloader/index.js:245:13)
    at Hook.wrapper [as loadUserConfig] (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/@sailshq/lodash/lib/index.js:3250:19)
    at Hook.loadModules (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/sails/lib/hooks/userconfig/index.js:41:27)
    at Hook.wrapper [as loadModules] (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/@sailshq/lodash/lib/index.js:3250:19)

**Comment by theo4u** [comment]
hmmm taking a look at it now

**Comment by anasuya1117** [comment]
One more issue I am facing,

`verbose: A socket is being allowed to connect, but the session could not be loaded.  Will create an empty, one-time session to use for the life of the socket connection.  Details:
 Error: Session could not be loaded
    at _createError (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/sails/lib/hooks/session/index.js:31:19)
    at Immediate._onImmediate (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/sails/lib/hooks/session/index.js:34:11)
    at runCallback (timers.js:804:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
`

This error is coming ,anyways its not hampering any work,,,still ,please let me know if I need to add anymore configuration

**Comment by anasuya1117** [comment]
the issue is coming in `swaggerJsonPath: sails.config.appPath + "/swagger/swagger.json"` this line 
`sails.config.appPath` is throwing this error actually

**Comment by theo4u** [comment]
that sails is undefined right ?

**Comment by anasuya1117** [comment]
yes

**Comment by theo4u** [comment]
Oh yea, check your configuration ( `config/globals.js`) and see if `sails` is true

**Comment by anasuya1117** [comment]
Tried updating `config/globals.js` , but no luck.
created a demo repo [https://github.com/anasuya1117/myToDoApp](myTodoApp) ,please have a look

**Comment by theo4u** [comment]
Taking a look later today 👍

**Comment by theo4u** [comment]
Seen the error, in your `swaggergenerator.js` you added `swaggerJsonPath` to use`sails.config` which is the default path, if you want to stick with the default path no need for adding it, remove it from your `swaggergenerator.js`. If you want to change the folder, then you do something like this 
 `swaggerJsonPath: "./assets/swagger/swagger.json"` --> using the absolute path relative to the project

**Comment by anasuya1117** [comment]
great, It worked !!! Thanks a lot for your help.
