### ISSUE TITLE
Getting error on sails lift

### ISSUE THREAD

**Issue by anasuya1117** [theo4u/sails-hook-swagger-generator#5]
A hook (`swagger-generator`) failed to load!
error: TypeError: Cannot read property 'trim' of undefined
at /home/anasuya/Documents/FrescoPlay/date-api/node_modules/sails-hook-swagger-generator/lib/parsers.js:77:39
    at baseFor (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/lodash/index.js:2007:13)
    at baseForOwn (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/lodash/index.js:2061:14)
    at baseEach (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/lodash/index.js:1820:16)
    at Function.forEach (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/lodash/index.js:5953:11)
    at Object._parseRoutes [as routes] (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/sails-hook-swagger-generator/lib/parsers.js:56:7)
    at Object._generateRoutes [as routes] (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/sails-hook-swagger-generator/lib/generators.js:149:26)
    at module.exports (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/sails-hook-swagger-generator/lib/swaggerDoc.js:15:38)
    at Hook.initialize (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/sails-hook-swagger-generator/index.js:39:13)
    at Hook.wrapper [as initialize] (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/@sailshq/lodash/lib/index.js:3250:19)

**Comment by theo4u** [comment]
hey @anasuya1117 one of your `routes.js` entry is using `path:target`(`/user/foo:target`) and this library only considered `verb path:target`(`post /user/foo:target`). Going to fix it soon to follow [Sails Routes Address](http://sailsjs.com/documentation/concepts/routes/custom-routes#?route-address)

**Comment by anasuya1117** [comment]
is this issue resolved ???
Now this issue is coming 
error: A hook (`swagger-generator`) failed to load!
verbose: Lowering sails...
verbose: Sent kill signal to child process (5876)...
verbose: Shutting down HTTP server...
verbose: HTTP server shut down successfully.
error: TypeError: Cannot read property 'http_method' of undefined
    at /home/anasuya/Documents/FrescoPlay/date-api/node_modules/sails-hook-swagger-generator/lib/parsers.js:103:22
    at /home/anasuya/Documents/FrescoPlay/date-api/node_modules/lodash/index.js:3073:15
    at baseForOwn (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/lodash/index.js:2046:14)
    at /home/anasuya/Documents/FrescoPlay/date-api/node_modules/lodash/index.js:3043:18
    at Function.<anonymous> (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/lodash/index.js:3346:13)
    at Object._parseRoutes [as routes] (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/sails-hook-swagger-generator/lib/parsers.js:67:7)
    at Object._generateRoutes [as routes] (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/sails-hook-swagger-generator/lib/generators.js:149:26)
    at module.exports (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/sails-hook-swagger-generator/lib/swaggerDoc.js:15:38)
    at Hook.initialize (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/sails-hook-swagger-generator/index.js:44:13)
    at Hook.wrapper [as initialize] (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/@sailshq/lodash/lib/index.js:3250:19)
    at /home/anasuya/Documents/FrescoPlay/date-api/node_modules/sails/lib/hooks/index.js:88:16
    at /home/anasuya/Documents/FrescoPlay/date-api/node_modules/sails/node_modules/async/lib/async.js:52:16
    at /home/anasuya/Documents/FrescoPlay/date-api/node_modules/sails/node_modules/async/lib/async.js:548:17
    at /home/anasuya/Documents/FrescoPlay/date-api/node_modules/sails/node_modules/async/lib/async.js:542:17
    at _arrayEach (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/sails/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete (/home/anasuya/Documents/FrescoPlay/date-api/node_modules/sails/node_modules/async/lib/async.js:541:13)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
