### ISSUE TITLE
Cannot read property 'http_method' of undefined

### ISSUE THREAD

**Issue by SeppPenner** [theo4u/sails-hook-swagger-generator#7]
I'm getting the following error when starting the generator with `sails lift`: 
The ... stand for the full path (I don't want to share here).

```
A hook (`swagger-generator`) failed to load!
error: TypeError: Cannot read property 'http_method' of undefined
    at ...\node_modules\sails-hook-swagger-generator\lib\parsers.js:103:21
    at ...\node_modules\lodash\index.js:3073:15
    at baseForOwn (...\node_modules\lodash\index.js:2046:14)
    at ...\node_modules\lodash\index.js:3043:18
    at Function.<anonymous> (...\node_modules\lodash\index.js:3346:13)
    at Object._parseRoutes [as routes] (...\node_modules\sails-hook-swagger-generator\lib\parsers.js:67:7)
    at Object._generateRoutes [as routes] (...\node_modules\sails-hook-swagger-generator\lib\generators.js:149:26)
    at module.exports (...\node_modules\sails-hook-swagger-generator\lib\swaggerDoc.js:15:38)
    at Hook.initialize (...\node_modules\sails-hook-swagger-generator\index.js:39:13)
    at Hook.wrapper [as initialize] (...\node_modules\sails\node_modules\@sailshq\lodash\lib\index.js:3250:19)
    at ...\node_modules\sails\lib\hooks\index.js:88:16
    at ...\node_modules\sails\node_modules\async\lib\async.js:52:16
    at ...\node_modules\sails\node_modules\async\lib\async.js:548:17
    at ...\node_modules\sails\node_modules\async\lib\async.js:542:17
    at _arrayEach (...\node_modules\sails\node_modules\async\lib\async.js:85:13)
    at Immediate.taskComplete (...\node_modules\sails\node_modules\async\lib\async.js:541:13)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

```

Do you have any suggestions here?

**Comment by theo4u** [comment]
How's your route formatted `routes.js`, allowed routes [here](http://sailsjs.com/documentation/concepts/routes/custom-routes#?route-address) , let me see your format

**Comment by SeppPenner** [comment]
```javascript
/**
 * Route Mappings
 * (sails.config.routes)
 *
 * Your routes map URLs to views and controllers.
 *
 * If Sails receives a URL that doesn't match any of the routes below,
 * it will check for matching files (images, scripts, stylesheets, etc.)
 * in your assets directory.  e.g. `http://localhost:1337/images/foo.jpg`
 * might match an image file: `/assets/images/foo.jpg`
 *
 * Finally, if those don't match either, the default 404 handler is triggered.
 * See `api/responses/notFound.js` to adjust your app's 404 logic.
 *
 * Note: Sails doesn't ACTUALLY serve stuff from `assets`-- the default Gruntfile in Sails copies
 * flat files from `assets` to `.tmp/public`.  This allows you to do things like compile LESS or
 * CoffeeScript for the front-end.
 *
 * For more information on configuring custom routes, check out:
 * http://sailsjs.org/#!/documentation/concepts/Routes/RouteTargetSyntax.html
 */

module.exports.routes = {

  /***************************************************************************
  *                                                                          *
  * Make the view located at `views/homepage.ejs` (or `views/homepage.jade`, *
  * etc. depending on your default view engine) your home page.              *
  *                                                                          *
  * (Alternatively, remove this and add an `index.html` file in your         *
  * `assets` directory)                                                      *
  *                                                                          *
  ***************************************************************************/

  '/': {
    view: 'homepage'
  },

  /***************************************************************************
  *                                                                          *
  * Custom routes here...                                                    *
  *                                                                          *
  * If a request to a URL doesn't match any of the custom routes above, it   *
  * is matched against Sails route blueprints. See `config/blueprints.js`    *
  * for configuration options and examples.                                  *
  *                                                                          *
  ***************************************************************************/
  
  'get /api/user/getAll': 'UserController.getUsers',
  'post /api/user/register': 'UserController.registerUser',
  'post /api/user/login': 'UserController.loginUser',
  'post /api/user/auth': 'UserController.authenticateUser'
};

```

**Comment by SeppPenner** [comment]
I've only added a model for a user, a controller and so on using `sails generate api user`. The rest is the sails standard config.

**Comment by theo4u** [comment]
comment out this 
```js
 '/': {
    view: 'homepage'
  },
``` 

and give it  a try.

**Comment by SeppPenner** [comment]
Well, this seems to fix it. Thanks ;)
